name: Check Commits

on: [push]

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Commits
        run: |
          commit_count=$(git rev-list --count HEAD)
          if [ "$commit_count" -gt 1 ]; then
              echo "Pass!"
          else
              echo "Fail!"
              exit 1
